version: "3.4"
services:
  app:
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "5035:80"
  postgres:
    build:
      context: .
      dockerfile: psql/Dockerfile 
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./psql/sample_data/1-fill.sh:/docker-entrypoint-initdb.d/1-fill.sh
      - ./psql/sample_data/2-sample-data.sql:/docker-entrypoint-initdb.d/2-sample-data.sql
    environment:
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=111
      - SCHEMA=public
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data: